//go:build !ignore_autogenerated

package v1alpha1

import (
	corev1 "k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	clusterv1 "sigs.k8s.io/cluster-api/api/v1beta1"
)



func (in *HetznerRobotCluster) DeepCopyInto(out *HetznerRobotCluster) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

func (in *HetznerRobotCluster) DeepCopy() *HetznerRobotCluster {
	if in == nil {
		return nil
	}
	out := new(HetznerRobotCluster)
	in.DeepCopyInto(out)
	return out
}

func (in *HetznerRobotCluster) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *HetznerRobotClusterList) DeepCopyInto(out *HetznerRobotClusterList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]HetznerRobotCluster, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *HetznerRobotClusterList) DeepCopy() *HetznerRobotClusterList {
	if in == nil {
		return nil
	}
	out := new(HetznerRobotClusterList)
	in.DeepCopyInto(out)
	return out
}

func (in *HetznerRobotClusterList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *HetznerRobotClusterSpec) DeepCopyInto(out *HetznerRobotClusterSpec) {
	*out = *in
	out.ControlPlaneEndpoint = in.ControlPlaneEndpoint
	out.RobotSecretRef = in.RobotSecretRef
	out.SSHSecretRef = in.SSHSecretRef
	if in.VLANConfig != nil {
		in, out := &in.VLANConfig, &out.VLANConfig
		*out = new(VLANConfig)
		**out = **in
	}
}

func (in *HetznerRobotClusterSpec) DeepCopy() *HetznerRobotClusterSpec {
	if in == nil {
		return nil
	}
	out := new(HetznerRobotClusterSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *HetznerRobotClusterStatus) DeepCopyInto(out *HetznerRobotClusterStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make(clusterv1.Conditions, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *HetznerRobotClusterStatus) DeepCopy() *HetznerRobotClusterStatus {
	if in == nil {
		return nil
	}
	out := new(HetznerRobotClusterStatus)
	in.DeepCopyInto(out)
	return out
}

// HetznerRobotMachine DeepCopy

func (in *HetznerRobotMachine) DeepCopyInto(out *HetznerRobotMachine) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

func (in *HetznerRobotMachine) DeepCopy() *HetznerRobotMachine {
	if in == nil {
		return nil
	}
	out := new(HetznerRobotMachine)
	in.DeepCopyInto(out)
	return out
}

func (in *HetznerRobotMachine) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *HetznerRobotMachineList) DeepCopyInto(out *HetznerRobotMachineList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]HetznerRobotMachine, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *HetznerRobotMachineList) DeepCopy() *HetznerRobotMachineList {
	if in == nil {
		return nil
	}
	out := new(HetznerRobotMachineList)
	in.DeepCopyInto(out)
	return out
}

func (in *HetznerRobotMachineList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *HetznerRobotMachineSpec) DeepCopyInto(out *HetznerRobotMachineSpec) {
	*out = *in
	if in.ProviderID != nil {
		in, out := &in.ProviderID, &out.ProviderID
		*out = new(string)
		**out = **in
	}
	if in.HostRef != nil {
		in, out := &in.HostRef, &out.HostRef
		*out = new(corev1.LocalObjectReference)
		**out = **in
	}
	if in.HostSelector != nil {
		in, out := &in.HostSelector, &out.HostSelector
		*out = new(metav1.LabelSelector)
		(*in).DeepCopyInto(*out)
	}
}

func (in *HetznerRobotMachineSpec) DeepCopy() *HetznerRobotMachineSpec {
	if in == nil {
		return nil
	}
	out := new(HetznerRobotMachineSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *HetznerRobotMachineStatus) DeepCopyInto(out *HetznerRobotMachineStatus) {
	*out = *in
	if in.Addresses != nil {
		in, out := &in.Addresses, &out.Addresses
		*out = make([]clusterv1.MachineAddress, len(*in))
		copy(*out, *in)
	}
	if in.FailureReason != nil {
		in, out := &in.FailureReason, &out.FailureReason
		*out = new(string)
		**out = **in
	}
	if in.FailureMessage != nil {
		in, out := &in.FailureMessage, &out.FailureMessage
		*out = new(string)
		**out = **in
	}
	if in.LastRetryTimestamp != nil {
		in, out := &in.LastRetryTimestamp, &out.LastRetryTimestamp
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make(clusterv1.Conditions, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *HetznerRobotMachineStatus) DeepCopy() *HetznerRobotMachineStatus {
	if in == nil {
		return nil
	}
	out := new(HetznerRobotMachineStatus)
	in.DeepCopyInto(out)
	return out
}

// HetznerRobotMachineTemplate DeepCopy

func (in *HetznerRobotMachineTemplate) DeepCopyInto(out *HetznerRobotMachineTemplate) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

func (in *HetznerRobotMachineTemplate) DeepCopy() *HetznerRobotMachineTemplate {
	if in == nil {
		return nil
	}
	out := new(HetznerRobotMachineTemplate)
	in.DeepCopyInto(out)
	return out
}

func (in *HetznerRobotMachineTemplate) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *HetznerRobotMachineTemplateList) DeepCopyInto(out *HetznerRobotMachineTemplateList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]HetznerRobotMachineTemplate, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *HetznerRobotMachineTemplateList) DeepCopy() *HetznerRobotMachineTemplateList {
	if in == nil {
		return nil
	}
	out := new(HetznerRobotMachineTemplateList)
	in.DeepCopyInto(out)
	return out
}

func (in *HetznerRobotMachineTemplateList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *HetznerRobotMachineTemplateSpec) DeepCopyInto(out *HetznerRobotMachineTemplateSpec) {
	*out = *in
	in.Template.DeepCopyInto(&out.Template)
}

func (in *HetznerRobotMachineTemplateSpec) DeepCopy() *HetznerRobotMachineTemplateSpec {
	if in == nil {
		return nil
	}
	out := new(HetznerRobotMachineTemplateSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *HetznerRobotMachineTemplateResource) DeepCopyInto(out *HetznerRobotMachineTemplateResource) {
	*out = *in
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
}

func (in *HetznerRobotMachineTemplateResource) DeepCopy() *HetznerRobotMachineTemplateResource {
	if in == nil {
		return nil
	}
	out := new(HetznerRobotMachineTemplateResource)
	in.DeepCopyInto(out)
	return out
}

func (in *HetznerRobotMachineTemplateStatus) DeepCopyInto(out *HetznerRobotMachineTemplateStatus) {
	*out = *in
}

func (in *HetznerRobotMachineTemplateStatus) DeepCopy() *HetznerRobotMachineTemplateStatus {
	if in == nil {
		return nil
	}
	out := new(HetznerRobotMachineTemplateStatus)
	in.DeepCopyInto(out)
	return out
}

// ─── HetznerRobotHost DeepCopy (generated) ────────────────────────────────────

func (in *HetznerRobotHost) DeepCopyInto(out *HetznerRobotHost) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

func (in *HetznerRobotHost) DeepCopy() *HetznerRobotHost {
	if in == nil {
		return nil
	}
	out := new(HetznerRobotHost)
	in.DeepCopyInto(out)
	return out
}

func (in *HetznerRobotHost) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *HetznerRobotHostList) DeepCopyInto(out *HetznerRobotHostList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]HetznerRobotHost, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *HetznerRobotHostList) DeepCopy() *HetznerRobotHostList {
	if in == nil {
		return nil
	}
	out := new(HetznerRobotHostList)
	in.DeepCopyInto(out)
	return out
}

func (in *HetznerRobotHostList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *HetznerRobotHostSpec) DeepCopyInto(out *HetznerRobotHostSpec) {
	*out = *in
}

func (in *HetznerRobotHostSpec) DeepCopy() *HetznerRobotHostSpec {
	if in == nil {
		return nil
	}
	out := new(HetznerRobotHostSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *HetznerRobotHostStatus) DeepCopyInto(out *HetznerRobotHostStatus) {
	*out = *in
	if in.MachineRef != nil {
		in, out := &in.MachineRef, &out.MachineRef
		*out = new(MachineReference)
		**out = **in
	}
}

func (in *HetznerRobotHostStatus) DeepCopy() *HetznerRobotHostStatus {
	if in == nil {
		return nil
	}
	out := new(HetznerRobotHostStatus)
	in.DeepCopyInto(out)
	return out
}

func (in *MachineReference) DeepCopyInto(out *MachineReference) {
	*out = *in
}

func (in *MachineReference) DeepCopy() *MachineReference {
	if in == nil {
		return nil
	}
	out := new(MachineReference)
	in.DeepCopyInto(out)
	return out
}

func (in *VLANConfig) DeepCopyInto(out *VLANConfig) {
	*out = *in
}

func (in *VLANConfig) DeepCopy() *VLANConfig {
	if in == nil {
		return nil
	}
	out := new(VLANConfig)
	in.DeepCopyInto(out)
	return out
}

// ─── HetznerRobotRemediation DeepCopy ──────────────────────────────────────────

func (in *HetznerRobotRemediation) DeepCopyInto(out *HetznerRobotRemediation) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

func (in *HetznerRobotRemediation) DeepCopy() *HetznerRobotRemediation {
	if in == nil {
		return nil
	}
	out := new(HetznerRobotRemediation)
	in.DeepCopyInto(out)
	return out
}

func (in *HetznerRobotRemediation) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *HetznerRobotRemediationList) DeepCopyInto(out *HetznerRobotRemediationList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]HetznerRobotRemediation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *HetznerRobotRemediationList) DeepCopy() *HetznerRobotRemediationList {
	if in == nil {
		return nil
	}
	out := new(HetznerRobotRemediationList)
	in.DeepCopyInto(out)
	return out
}

func (in *HetznerRobotRemediationList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *HetznerRobotRemediationSpec) DeepCopyInto(out *HetznerRobotRemediationSpec) {
	*out = *in
}

func (in *HetznerRobotRemediationSpec) DeepCopy() *HetznerRobotRemediationSpec {
	if in == nil {
		return nil
	}
	out := new(HetznerRobotRemediationSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *HetznerRobotRemediationStatus) DeepCopyInto(out *HetznerRobotRemediationStatus) {
	*out = *in
	if in.LastRemediated != nil {
		in, out := &in.LastRemediated, &out.LastRemediated
		*out = (*in).DeepCopy()
	}
}

func (in *HetznerRobotRemediationStatus) DeepCopy() *HetznerRobotRemediationStatus {
	if in == nil {
		return nil
	}
	out := new(HetznerRobotRemediationStatus)
	in.DeepCopyInto(out)
	return out
}

func (in *RemediationStrategy) DeepCopyInto(out *RemediationStrategy) {
	*out = *in
}

func (in *RemediationStrategy) DeepCopy() *RemediationStrategy {
	if in == nil {
		return nil
	}
	out := new(RemediationStrategy)
	in.DeepCopyInto(out)
	return out
}

// ─── HetznerRobotRemediationTemplate DeepCopy ─────────────────────────────────

func (in *HetznerRobotRemediationTemplate) DeepCopyInto(out *HetznerRobotRemediationTemplate) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
}

func (in *HetznerRobotRemediationTemplate) DeepCopy() *HetznerRobotRemediationTemplate {
	if in == nil {
		return nil
	}
	out := new(HetznerRobotRemediationTemplate)
	in.DeepCopyInto(out)
	return out
}

func (in *HetznerRobotRemediationTemplate) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *HetznerRobotRemediationTemplateList) DeepCopyInto(out *HetznerRobotRemediationTemplateList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]HetznerRobotRemediationTemplate, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *HetznerRobotRemediationTemplateList) DeepCopy() *HetznerRobotRemediationTemplateList {
	if in == nil {
		return nil
	}
	out := new(HetznerRobotRemediationTemplateList)
	in.DeepCopyInto(out)
	return out
}

func (in *HetznerRobotRemediationTemplateList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *HetznerRobotRemediationTemplateSpec) DeepCopyInto(out *HetznerRobotRemediationTemplateSpec) {
	*out = *in
	in.Template.DeepCopyInto(&out.Template)
}

func (in *HetznerRobotRemediationTemplateSpec) DeepCopy() *HetznerRobotRemediationTemplateSpec {
	if in == nil {
		return nil
	}
	out := new(HetznerRobotRemediationTemplateSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *HetznerRobotRemediationTemplateResource) DeepCopyInto(out *HetznerRobotRemediationTemplateResource) {
	*out = *in
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
}

func (in *HetznerRobotRemediationTemplateResource) DeepCopy() *HetznerRobotRemediationTemplateResource {
	if in == nil {
		return nil
	}
	out := new(HetznerRobotRemediationTemplateResource)
	in.DeepCopyInto(out)
	return out
}
