//go:build !ignore_autogenerated

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
	clusterv1 "sigs.k8s.io/cluster-api/api/v1beta1"
)

func (in *HetznerRobotCluster) DeepCopyInto(out *HetznerRobotCluster) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

func (in *HetznerRobotCluster) DeepCopy() *HetznerRobotCluster {
	if in == nil {
		return nil
	}
	out := new(HetznerRobotCluster)
	in.DeepCopyInto(out)
	return out
}

func (in *HetznerRobotCluster) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *HetznerRobotClusterList) DeepCopyInto(out *HetznerRobotClusterList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]HetznerRobotCluster, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *HetznerRobotClusterList) DeepCopy() *HetznerRobotClusterList {
	if in == nil {
		return nil
	}
	out := new(HetznerRobotClusterList)
	in.DeepCopyInto(out)
	return out
}

func (in *HetznerRobotClusterList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *HetznerRobotClusterSpec) DeepCopyInto(out *HetznerRobotClusterSpec) {
	*out = *in
	out.ControlPlaneEndpoint = in.ControlPlaneEndpoint
	out.RobotSecretRef = in.RobotSecretRef
	out.SSHSecretRef = in.SSHSecretRef
}

func (in *HetznerRobotClusterSpec) DeepCopy() *HetznerRobotClusterSpec {
	if in == nil {
		return nil
	}
	out := new(HetznerRobotClusterSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *HetznerRobotClusterStatus) DeepCopyInto(out *HetznerRobotClusterStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make(clusterv1.Conditions, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *HetznerRobotClusterStatus) DeepCopy() *HetznerRobotClusterStatus {
	if in == nil {
		return nil
	}
	out := new(HetznerRobotClusterStatus)
	in.DeepCopyInto(out)
	return out
}

// HetznerRobotMachine DeepCopy

func (in *HetznerRobotMachine) DeepCopyInto(out *HetznerRobotMachine) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

func (in *HetznerRobotMachine) DeepCopy() *HetznerRobotMachine {
	if in == nil {
		return nil
	}
	out := new(HetznerRobotMachine)
	in.DeepCopyInto(out)
	return out
}

func (in *HetznerRobotMachine) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *HetznerRobotMachineList) DeepCopyInto(out *HetznerRobotMachineList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]HetznerRobotMachine, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *HetznerRobotMachineList) DeepCopy() *HetznerRobotMachineList {
	if in == nil {
		return nil
	}
	out := new(HetznerRobotMachineList)
	in.DeepCopyInto(out)
	return out
}

func (in *HetznerRobotMachineList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *HetznerRobotMachineSpec) DeepCopyInto(out *HetznerRobotMachineSpec) {
	*out = *in
	if in.ProviderID != nil {
		in, out := &in.ProviderID, &out.ProviderID
		*out = new(string)
		**out = **in
	}
}

func (in *HetznerRobotMachineSpec) DeepCopy() *HetznerRobotMachineSpec {
	if in == nil {
		return nil
	}
	out := new(HetznerRobotMachineSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *HetznerRobotMachineStatus) DeepCopyInto(out *HetznerRobotMachineStatus) {
	*out = *in
	if in.Addresses != nil {
		in, out := &in.Addresses, &out.Addresses
		*out = make([]clusterv1.MachineAddress, len(*in))
		copy(*out, *in)
	}
	if in.FailureReason != nil {
		in, out := &in.FailureReason, &out.FailureReason
		*out = new(string)
		**out = **in
	}
	if in.FailureMessage != nil {
		in, out := &in.FailureMessage, &out.FailureMessage
		*out = new(string)
		**out = **in
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make(clusterv1.Conditions, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *HetznerRobotMachineStatus) DeepCopy() *HetznerRobotMachineStatus {
	if in == nil {
		return nil
	}
	out := new(HetznerRobotMachineStatus)
	in.DeepCopyInto(out)
	return out
}

// HetznerRobotMachineTemplate DeepCopy

func (in *HetznerRobotMachineTemplate) DeepCopyInto(out *HetznerRobotMachineTemplate) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

func (in *HetznerRobotMachineTemplate) DeepCopy() *HetznerRobotMachineTemplate {
	if in == nil {
		return nil
	}
	out := new(HetznerRobotMachineTemplate)
	in.DeepCopyInto(out)
	return out
}

func (in *HetznerRobotMachineTemplate) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *HetznerRobotMachineTemplateList) DeepCopyInto(out *HetznerRobotMachineTemplateList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]HetznerRobotMachineTemplate, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *HetznerRobotMachineTemplateList) DeepCopy() *HetznerRobotMachineTemplateList {
	if in == nil {
		return nil
	}
	out := new(HetznerRobotMachineTemplateList)
	in.DeepCopyInto(out)
	return out
}

func (in *HetznerRobotMachineTemplateList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *HetznerRobotMachineTemplateSpec) DeepCopyInto(out *HetznerRobotMachineTemplateSpec) {
	*out = *in
	in.Template.DeepCopyInto(&out.Template)
}

func (in *HetznerRobotMachineTemplateSpec) DeepCopy() *HetznerRobotMachineTemplateSpec {
	if in == nil {
		return nil
	}
	out := new(HetznerRobotMachineTemplateSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *HetznerRobotMachineTemplateResource) DeepCopyInto(out *HetznerRobotMachineTemplateResource) {
	*out = *in
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
}

func (in *HetznerRobotMachineTemplateResource) DeepCopy() *HetznerRobotMachineTemplateResource {
	if in == nil {
		return nil
	}
	out := new(HetznerRobotMachineTemplateResource)
	in.DeepCopyInto(out)
	return out
}

func (in *HetznerRobotMachineTemplateStatus) DeepCopyInto(out *HetznerRobotMachineTemplateStatus) {
	*out = *in
	if in.Capacity != nil {
		in, out := &in.Capacity, &out.Capacity
		*out = make(clusterv1.ResourceTable, len(*in))
		for key, val := range *in {
			(*out)[key] = val.DeepCopy()
		}
	}
}

func (in *HetznerRobotMachineTemplateStatus) DeepCopy() *HetznerRobotMachineTemplateStatus {
	if in == nil {
		return nil
	}
	out := new(HetznerRobotMachineTemplateStatus)
	in.DeepCopyInto(out)
	return out
}
